name: XG7Lobby
version: '${version}'
main: com.xg7plugins.xg7lobby.plugin.XG7LobbyLoader
api-version: '1.16'

softdepend:
  - "XG7Plugins"
  - "LuckPerms"
  - "Multiverse-Inventories"
  - "nLogin"
  
permissions:
  xg7lobby.admin:
    description: Permission to use the admin commands.
    default: op
    children:
      xg7lobby.command.*: true
      xg7lobby.moderation.*: true
      xg7lobby.attack: true
      xg7lobby.pvp: true
      xg7lobby.chat.*: true
      xg7lobby.inv: true
      xg7lobby.build: true
      xg7lobby.command_block_bypass: true

  xg7lobby.command.*:
    description: Permission to use all commands.
    default: op
    children:
      xg7lobby.command.fly: true
      xg7lobby.command.fly-other: true
      xg7lobby.command.lockchat: true
      xg7lobby.command.gamemode: true
      xg7lobby.command.gamemode-others: true
      xg7lobby.command.build-other: true
      xg7lobby.command.build: true
      xg7lobby.command.lobby.*: true
      xg7lobby.command.infractions: true
      xg7lobby.command.infractions-other: true
      xg7lobby.command.resetstats: true
      xg7lobby.command.vanish: true
      xg7lobby.command.help: true

  xg7lobby.command.lobby.*:
    description: Permission to use all lobby commands.
    default: op
    children:
      xg7lobby.command.lobby.teleport: true
      xg7lobby.command.lobby.teleport-id: true
      xg7lobby.command.lobby.teleport-others: true
      xg7lobby.command.lobby.set: true
      xg7lobby.command.lobby.delete: true
      xg7lobby.command.lobby.bypass-cooldown: true
      xg7lobby.command.lobby.see-lobbies: true


  xg7lobby.moderation.*:
    description: Permission to use all moderation commands.
    default: op
    children:
      xg7lobby.moderation.kick: true
      xg7lobby.moderation.ban: true
      xg7lobby.moderation.unban: true
      xg7lobby.moderation.mute: true
      xg7lobby.moderation.unmute: true
      xg7lobby.moderation.tempban: true
      xg7lobby.moderation.tempmute: true
      xg7lobby.moderation.infraction.*: true

  xg7lobby.moderation.infraction.*:
    description: Infraction command
    default: op
    children:
      xg7lobby.moderation.infraction.add: true
      xg7lobby.moderation.infraction.pardon: true

  xg7lobby.chat.*:
    description: Permission to use all chat restrictions.
    default: op
    children:
      xg7lobby.chat.swear: true
      xg7lobby.chat.ignore-lock: true
      xg7lobby.chat.spam: true
