name: XG7Lobby
version: '${version}'
main: com.xg7plugins.xg7lobby.plugin.XG7LobbyLoader
api-version: '1.16'

softdepend:
  - "XG7Plugins"
  - "LuckPerms"
  - "Multiverse-Inventories"
  - "nLogin"
  
permissions:
  xg7lobby.admin:
    description: Permission to use the admin commands.
    default: op
    children:
      xg7lobby.command.*: true
      xg7lobby.moderation.*: true
      xg7lobby.attack: true
      xg7lobby.pvp: true
      xg7lobby.chat.*: true
      xg7lobby.inv: true
      xg7lobby.build: true
      xg7lobby.command_block_bypass: true

  xg7lobby.command.*:
    description: Permission to use all commands.
    default: op
    children:
      xg7lobby.command.fly: true
      xg7lobby.command.fly-other: true
      xg7lobby.command.lockchat: true
      xg7lobby.command.gamemode: true
      xg7lobby.command.gamemode-others: true
      xg7lobby.command.build-other: true
      xg7lobby.command.build: true
      xg7lobby.command.lobby.*: true
      xg7lobby.command.infractions: true
      xg7lobby.command.infractions-other: true
      xg7lobby.command.resetstats: true
      xg7lobby.command.vanish: true
      xg7lobby.command.help: true
      xg7lobby.command.clearchat: true
      xg7lobby.command.npcs: true
      xg7lobby.command.holograms: true

  xg7lobby.command.lobby.*:
    description: Permission to use all lobby commands.
    default: op
    children:
      xg7lobby.command.lobby.teleport: true
      xg7lobby.command.lobby.teleport-id: true
      xg7lobby.command.lobby.teleport-others: true
      xg7lobby.command.lobby.set: true
      xg7lobby.command.lobby.delete: true
      xg7lobby.command.lobby.bypass-cooldown: true
      xg7lobby.command.lobby.see-lobbies: true


  xg7lobby.command.clearchat:
    description: Allows clearing the chat via the custom clearchat command.
    default: false

  xg7lobby.command.fly:
    description: Allows using fly command/menu.
    default: false

  xg7lobby.command.fly-other:
    description: Allows toggling fly for other players.
    default: op

  xg7lobby.queue.priority:
    description: Grants priority in lobby queues.
    default: false

  xg7lobby.multi-jumps:
    description: Allows using multi-jumps when enabled in config.
    default: false

  xg7lobby.command_block_bypass:
    description: Bypass command blocking (anti-tab/blocked commands).
    default: op

  xg7lobby.command.build-other:
    description: Allows toggling build for other players.
    default: op

  xg7lobby.command.lockchat:
    description: Allows locking chat via commands.
    default: op

  xg7lobby.command.gamemode:
    description: Allows changing gamemode.
    default: false

  xg7lobby.command.gamemode-others:
    description: Allows changing other players' gamemode.
    default: op

  xg7lobby.moderation.*:
    description: Permission to use all moderation commands.
    default: op
    children:
      xg7lobby.moderation.kick: true
      xg7lobby.moderation.ban: true
      xg7lobby.moderation.unban: true
      xg7lobby.moderation.mute: true
      xg7lobby.moderation.unmute: true
      xg7lobby.moderation.tempban: true
      xg7lobby.moderation.tempmute: true
      xg7lobby.moderation.infraction.*: true

  xg7lobby.moderation.infraction.*:
    description: Infraction command
    default: op
    children:
      xg7lobby.moderation.infraction.add: true
      xg7lobby.moderation.infraction.pardon: true

  xg7lobby.chat.*:
    description: Permission to use all chat restrictions.
    default: op
    children:
      xg7lobby.chat.swear: true
      xg7lobby.chat.ignore-lock: true
      xg7lobby.chat.spam: true

  xg7lobby.command.queue:
    description: Permission to manage queues
    default: op
    children:
      xg7lobby.command.queue.add: true
      xg7lobby.command.queue.remove: true
      xg7lobby.command.queue.leave: true

  xg7lobby.command.settings:
    description: Allows using settings command
    default: false

  xg7lobby.command.resetstats:
    description: Allows resetting player stats
    default: op

  xg7lobby.command.open:
    description: Allows opening custom menus/forms
    default: false

  xg7lobby.command.execute:
    description: Allows executing configured actions via commands
    default: op

  xg7lobby.command.chat:
    description: Allows toggling chat visibility
    default: false

  xg7lobby.command.chat.tell:
    description: Allows sending messages via /chat tell when chat hidden
    default: false

  xg7lobby.command.npcs:
    description: Manage NPCs
    default: op
    children:
      xg7lobby.command.npcs.create: true
      xg7lobby.command.npcs.select: true
      xg7lobby.command.npcs.delete: true
      xg7lobby.command.npcs.tp: true
      xg7lobby.command.npcs.glow: true
      xg7lobby.command.npcs.type: true
      xg7lobby.command.npcs.skin: true
      xg7lobby.command.npcs.skin.url: true
      xg7lobby.command.npcs.skin.uuid: true
      xg7lobby.command.npcs.skin.player: true
      xg7lobby.command.npcs.skin.mirror: true
      xg7lobby.command.npcs.skin.reset: true
      xg7lobby.command.npcs.options: true
      xg7lobby.command.npcs.name: true
      xg7lobby.command.npcs.name.addline: true
      xg7lobby.command.npcs.name.removeline: true
      xg7lobby.command.npcs.name.editline: true
      xg7lobby.command.npcs.name.options: true

  xg7lobby.command.holograms:
    description: Manage holograms
    default: op
    children:
      xg7lobby.command.holograms.create: true
      xg7lobby.command.holograms.delete: true
      xg7lobby.command.holograms.teleport: true
      xg7lobby.command.holograms.actions: true
      xg7lobby.command.holograms.lines: true
      xg7lobby.command.holograms.select: true
      xg7lobby.command.holograms.save: true

  xg7lobby.command.holograms.lines:
    description: Hologram lines management
    default: op
    children:
      xg7lobby.command.holograms.lines.add: true
      xg7lobby.command.holograms.lines.remove: true
      xg7lobby.command.holograms.lines.edit: true
      xg7lobby.command.holograms.lines.equip: true
      xg7lobby.command.holograms.lines.options: true
      xg7lobby.command.holograms.lines.options.list: true
      xg7lobby.command.holograms.lines.options.set: true

  xg7lobby.command.holograms.actions:
    description: Hologram actions management
    default: op
    children:
        xg7lobby.command.holograms.actions.add: true
        xg7lobby.command.holograms.actions.edit: true
        xg7lobby.command.holograms.actions.remove: true
        xg7lobby.command.holograms.actions.list: true

